const playlistsTypes = {
  FETCH_PLAYLISTS_PENDING: 'FETCH_PLAYLISTS_PENDING',
  FETCH_PLAYLISTS_SUCCESS: 'FETCH_PLAYLISTS_SUCCESS',
  FETCH_PLAYLISTS_FAILURE: 'FETCH_PLAYLISTS_FAILURE'
};

export default playlistsTypes;
